services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: dbox-db:prod
    container_name: dbox-db-prod
    secrets:
      - db_name
      - db_user
      - db_password
      - db_django_password
    environment:
      - POSTGRES_DB_FILE=/run/secrets/db_name
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - prod_db_data:/var/lib/postgresql/data
    networks:
      - prod_orm

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dbox-backend:prod
    container_name: dbox-backend-prod
    secrets:
      - db_name
      - db_user
      - db_django_password
      - django_key
    volumes:
      - prod_media_files:/media
      - prod_static_files:/usr/share/nginx/html/static
    networks:
      - prod_orm
      - prod_api

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: dbox-frontend:prod
    container_name: dbox-frontend-prod
    volumes:
      - prod_media_files:/usr/share/nginx/html/media
      - prod_static_files:/usr/share/nginx/html/static/django
    networks:
      - prod_api
    ports:
      - "80:80"

secrets:
  db_name:
    file: ./.secrets/prod/db_name.txt
  db_user:
    file: ./.secrets/prod/db_user.txt
  db_password:
    file: ./.secrets/prod/db_password.txt
  db_django_password:
    file: ./.secrets/prod/db_django_password.txt
  django_key:
    file: ./.secrets/prod/django_key.txt

volumes:
  prod_db_data:
  prod_media_files:
  prod_static_files:

networks:
  prod_api:
  prod_orm: 
