services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: dbox-db:dev
    container_name: dbox-db-dev
    secrets:
      - db_name
      - db_user
      - db_password
      - db_django_password
    environment:
      - POSTGRES_DB_FILE=/run/secrets/db_name
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    networks:
      - dev_orm

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dbox-backend:dev
    container_name: dbox-backend-dev
    secrets:
      - db_name
      - db_django_password
      - django_key
      - email_password
    volumes:
      - ./backend:/app
      - dev_media_files:/media
    networks:
      - dev_orm
      - dev_api
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: dbox-frontend:dev
    container_name: dbox-frontend-dev
    volumes:
      - ./frontend:/app:cache
      - dev_node_modules:/app/node_modules
    networks:
      - dev_api
    ports: 
      - "3000:3000"
    depends_on:
      - backend

secrets:
  db_name:
    file: ./.secrets/dev/db_name.txt
  db_user:
    file: ./.secrets/dev/db_user.txt
  db_password:
    file: ./.secrets/dev/db_password.txt
  db_django_password:
    file: ./.secrets/dev/db_django_password.txt
  django_key:
    file: ./.secrets/dev/django_key.txt
  email_password:
    file: ./.secrets/dev/email_password.txt

volumes:
  dev_db_data:
  dev_media_files:
  dev_node_modules:

networks:
  dev_api:
  dev_orm:
