services:
  db:
    image: postgres:alpine
    env_file: ./.env
    volumes:
      - ./db/db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: 
      - ./.env
      - ./backend/.env.backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app:cache
      - /app/node_modules 
    ports: 
      - "3000:3000"
    depends_on:
      - backend

