"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from .secrets import get_secret

WEBSITE_URL = "http://localhost:80"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

SECRET_KEY = get_secret("django_key")

DEBUG = False

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'backend',
    'dbox-fm.be',
    'www.dbox-fm.be',
]

# Application definition

INSTALLED_APPS = [
    'corsheaders',

    'users', # Move needed for new html on password reset

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'graphene_django',
    'rest_framework',

    'content',
    'moderation',
    'live',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # To search for templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': get_secret("db_name"),
        'USER': 'django',
        'PASSWORD': get_secret("db_django_password"),
        'HOST': 'db', # Refers to the 'db' container name from compose.yaml
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = '/usr/share/nginx/html/static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://dbox-fm.be",
    "https://dbox-fm.be",
]

CORS_ALLOW_METHODS = ['GET', 'POST', 'OPTIONS', 'DELETE', 'PATCH', 'PUT']

CORS_ALLOW_HEADERS = ["content-type", "authorization", "x-csrftoken"]

#CSRF_TRUSTED_ORIGINS = [
#    'http://localhost:3000',
#    'http://frontend:3000',
#    'http://0.0.0.0:3000',
#]

#CSRF_COOKIE_HTTPONLY = False
#CSRF_COOKIE_SAMESITE = 'Lax'
#CSRF_COOKIE_SECURE = False
#CSRF_USE_SESSIONS = False

GRAPHENE = {
    'SCHEMA': 'backend.schema.schema'
}

MEDIA_URL = "/media/"
MEDIA_ROOT = "/media"

SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = "Lax"

APPEND_SLASH = True

# EMAIL PARAMETERS #

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@dbox-fm.be'
EMAIL_HOST_PASSWORD = get_secret("email_password")
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST = "dbox-fm.be"
EMAIL_HOST_USER = "noreply@dbox-fm.be"
# ACCOUNT_EMAIL_VERIFICATION = 'none'

LOGGING = {
    'version': 1,
    'handlers': {
        'logstash': {
            'class': 'logstash.TCPLogstashHandler',
            'host': 'logstash',
            'port': 5000,
            'version': 1,
        },
    },
    'loggers': {
        'django': {
            'handlers': ['logstash'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.user': {
            'handlers': ['logstash'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.moderation': {
            'handlers': ['logstash'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.live': {
            'handlers': ['logstash'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.server': {
        'handlers': ['logstash'],
        'level': 'WARNING',  # Ignore INFO-level requests like 200 OK
        'propagate': False,
        },
        'django.request': {
        'handlers': ['logstash'],
        'level': 'ERROR',  # Only log failed requests
        'propagate': False,
        },
        'django.db.backends': {
            'level': 'WARNING',  # Avoid SQL logging unless needed
            'handlers': ['logstash'],
            'propagate': False,
        },
    }
}