# Generated by Django 5.1.7 on 2025-03-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='audio',
            field=models.FileField(upload_to='audio/'),
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
