# Generated by Django 5.1.7 on 2025-03-18 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_view_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.publication'),
        ),
    ]
