# Generated by Django 5.1.7 on 2025-03-18 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_view_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.publication'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.publication'),
        ),
    ]
