# Generated by Django 5.1.7 on 2025-03-19 07:33

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_view_publication_alter_vote_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='audio',
            field=models.FileField(upload_to='audio/', validators=[content.validators.validate_audio]),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/', validators=[content.validators.validate_image]),
        ),
    ]
