# Generated by Django 5.1.6 on 2025-02-28 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioLowQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio_low_quality/')),
            ],
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('audio_low_quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live.audiolowquality')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.publication')),
            ],
        ),
    ]
