# Generated by Django 5.1.7 on 2025-03-07 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.publication')),
            ],
        ),
    ]
