# Generated by Django 5.1.6 on 2025-02-28 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='audio_low_quality',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='live.audiolowquality'),
        ),
    ]
