# Generated by Django 5.1.6 on 2025-03-01 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_alter_scheduling_audio_low_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='audio_low_quality',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='live.audiolowquality'),
        ),
    ]
