input {
tcp {
port => 5000
codec => json
  }
}

filter {
  if [logger_name] == "django.user" {
    mutate {
      remove_field => [ "path", "request", "type", "host" , "taskName", "@version"]
    }
  }
  if [logger_name] == "django.moderation" {
    mutate {
      remove_field => [ "path", "request", "type", "host" , "taskName", "@version"]
    }
  }
  if [logger_name] == "django.utils.autoreload" {
    mutate {
      remove_field => [ "path", "request", "type", "host" , "taskName", "@version"]
    }
  }
}

output {
elasticsearch {
hosts => ["http://elasticsearch:9200"]
index => "app-logs-%{+YYYY.MM.dd}"
}
stdout {
codec => rubydebug
}
}