input {
  tcp {
    host => "0.0.0.0"
    port => 5000
    codec => json
    tags => ["django"]
  }

  # Default nginx syslog sends UDP datagrams
  udp {
    host => "0.0.0.0"
    port => 5001
    type => "syslog"
    codec => "line"
    tags => ["nginx"]
  }
}

filter {
  if "django" in [tags] {
    if [logger_name] == "django.user" or [logger_name] == "django.moderation" or [logger_name] == "django.utils.autoreload" {
      mutate {
        remove_field => ["path", "request", "type", "host", "taskName", "@version"]
      }
    }
  }

  if "nginx" in [tags] {
    # If using line codec, need to parse syslog format
    if [codec] == "line" {
      grok {
        match => { "message" => "%{COMBINEDAPACHELOG}" }
      }
      date {
        match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
        remove_field => [ "timestamp" ]
      }
    }
  }
}

output {
  if "nginx" in [tags] {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "${ELASTICSEARCH_USERNAME}"
      password => "${ELASTICSEARCH_PASSWORD}"
      index => "nginx-logs-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      user => "${ELASTICSEARCH_USERNAME}"
      password => "${ELASTICSEARCH_PASSWORD}"
      index => "app-logs-%{+YYYY.MM.dd}"
    }
  }

  stdout {
    codec => rubydebug
  }
}
